# Generated by Django 3.2 on 2021-05-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_seller',
            new_name='isSeller',
        ),
    ]
