# Generated by Django 3.2 on 2021-05-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='belongsTo',
            new_name='cartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='belongsTo',
            new_name='cart',
        ),
    ]
