# Generated by Django 3.2 on 2021-05-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210515_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartItem',
            new_name='belongsTo',
        ),
    ]
